@echo off
setlocal enabledelayedexpansion

echo ========================================
echo  Extract STRING_XXX Macros and Generate Header
echo ========================================
echo.

if not exist "lvgl_ex_language_string.c" (
    echo [ERROR] Cannot find lvgl_ex_language_string.c
    pause
    exit /b 1
)

set OUTPUT_FILE=lvgl_ex_language_string.h
set count=0

echo Generating %OUTPUT_FILE% ...
echo.

(
    echo /*
    echo     This file is automatically generated from lvgl_ex_language_string.c
    echo     Do not manually edit
    echo */
    echo.
    echo #ifndef __LVGL_EX_LANGUAGE_STRING_H__
    echo #define __LVGL_EX_LANGUAGE_STRING_H__
    echo.
    echo #ifdef __cplusplus
    echo extern "C" {
    echo #endif
    echo.

    for /f "tokens=2 delims=[]" %%a in ('findstr "\[STRING_" lvgl_ex_language_string.c') do (
        echo #define %%a !count!
        set /a count+=1
    )

    echo.
    echo #ifdef __cplusplus
    echo }
    echo #endif
    echo.
    echo #endif // __LVGL_EX_LANGUAGE_STRING_H__
) > "%OUTPUT_FILE%"

echo ========================================
echo [DONE] Generated %OUTPUT_FILE%
echo Total %count% macros extracted
echo ========================================

if %count%==0 (
    echo.
    echo [WARNING] No macros were extracted!
)

pause