#ifndef FONT_DECLARES_H_INCLUDED
#define FONT_DECLARES_H_INCLUDED


LV_FONT_DECLARE(font);
//LV_FONT_DECLARE(font_12);
//LV_FONT_DECLARE(font_18);
LV_FONT_DECLARE(font_24);
LV_FONT_DECLARE(font_30);
LV_FONT_DECLARE(font_36);
//LV_FONT_DECLARE(font_48);
//LV_FONT_DECLARE(font_60);



#endif // FONT_DECLARES_H_INCLUDED
